
nginx_pkgname: "nginx"
nginx_version: "1.18.0"

nginx_default_conf_dir: "/app/nginx/conf"
nginx_default_rootdir: "/app/nginx/html"

nginx_default_vhost_http_port: "80"
nginx_default_vhost_ssl_port: "443"

nginx_sid: "{{ inventory_hostname }}"

nginx_url_lists: []

nginx_setting:
  user: "{{ default_svc_user }}"
  worker_processes: "auto"
  worker_rlimit_nofile: 65536
  worker_connections: 16384
  client_header_timeout: "3m"
  client_body_timeout: "3m"
  send_timeout: "3m"
  client_max_body_size: "24m"
  client_body_buffer_size: "128k"
  connection_pool_size: "320"
  client_header_buffer_size: "1k"
  large_client_header_buffers: "4 8k"
  request_pool_size: "4k"
  output_buffers: "1 32k"
  postpone_output: "1460"
  keepalive_timeout: "65"
  keepalive_requests: "2048"

nginx_sites:
  01_test.example.com:
    listen_port: "80"
    server_name: "test.example.com"
    root: "/app/nginx/html"
    forwarding_proxy: "0"
    location_custom: |
      # letencrypt support
      location ~ /.well-known {
        allow all;
      }
    location_root: |
      return 200 'hi';
      add_header Content-type 'plain/text';
  02_test.example.com:
    listen_port: "80"
    server_name: "test2.example.com"
    root: "/app/nginx/html"
    forwarding_proxy: "0"
    location_custom: |
      # letencrypt support
      location ~ /.well-known {
        allow all;
      }
    location_root: |
      return 200 'hi 2';
      add_header Content-type 'text/plain';
